Header header

#*****************************************************************************
# This file contains message description to obtain status of command processing.
#*****************************************************************************
# Project:	yudrone
# Author:	Michael Dicke
# Repository:	https://github.com/mdicke2s/yudrone
#*****************************************************************************

# identification
int32 id

# is the command node locked by this command
bool isLocked

# status information
string status